name: ht_data_postgres
description: A Very Good Project created by Very Good CLI.
repository: https://github.com/headlines-toolkit/ht-data-postgres
publish_to: none

environment:
  sdk: ^3.8.0

dependencies: 
  ht_data_client:
    git:
      url: https://github.com/headlines-toolkit/ht-data-client.git
  ht_shared:
    git:
      url: https://github.com/headlines-toolkit/ht-shared.git
  logging: ^1.3.0
  postgres: ^3.5.6

dev_dependencies:
  equatable: ^2.0.7
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^9.0.0
